#   ___     _ _    _      _   
#  / _ \ __| (_)__| |__ _| |__
# | (_) / _` | / _` / _` | / /
#  \___/\__,_|_\__,_\__,_|_\_\
  
#Limit default yang akan dikasih ke player tanpa permissions khusus
default-home-limit: 3

#Limit khusus dengan permissions, bisa digunak untuk limit per rank, atau limit per player
permissions-limits:
  saungmc.home.vip:
    limit: 5
  saungmc.home.vip+:
    limit: 10
  saungmc.home.mvp:
    limit: 15
  saungmc.home.mvp+:
    limit: 20
  saungmc.home.mvp++:
    limit: 25
  saungmc.home.staff:
    limit: -1

#Kalian bisa menambahkan atau membuat permissions baru untuk mengatur limit baru
#Gunakan -1 untuk limit yang unlimited atau tidak terbatas
